# status bar 항상 표시
set -g status on

# 윈도우 리스트 스타일
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

# 색 강조
set -g window-status-style fg=colour250
set -g window-status-current-style fg=colour201,bold
